/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed. It is
// regenerated by Expo and provides `__DEV__`, asset module declarations, and
// the typed-routes definitions.
